### ISSUE TITLE
DBC file not loaded (bug ??)

### ISSUE THREAD

**Issue by Jdesprin** [collin80/SavvyCAN#107]
Hi,

I tried to load several dbc file , and it keeps displaying " No DBC database loaded". I used the ones provided in the example folder.

I used a socketcan connection on can0  and enter "0" as associated bus with the dbc file. However i don't see any changes. If this is not a bug can you guide me how to load the file ?

Thank you in advance for your help

**Comment by collin80** [comment]
Recent changes in the program lead to the status bar not being updated when you load DBC files. If you see them in the list on the "DBC File Manager" then the file is loaded. So, this is a bug in the program but it doesn't hurt anything, just mislead you.

**Comment by Jdesprin** [comment]
Oh i see, yes i confirm that it is just a display problem
