### ISSUE TITLE
Enable/Disable buses in connection window can get desynced from hardware

### ISSUE THREAD

**Issue by collin80** [collin80/SavvyCAN#116]
It seems that sometimes when you enable a bus in the connection window it doesn't really - and likewise for disabling. Investigate what is going on.

**Comment by collin80** [comment]
The connection window was overhauled and this does not seem to occur any longer.

**Comment by truss-cpi** [comment]
Seeing something similar with the current builds when using GVRET on a CANDue 2.2 shield.

Would you like a separate entry?
