### ISSUE TITLE
CANOpen heartbeat message shows corrupted data byte

### ISSUE THREAD

**Issue by collin80** [collin80/SavvyCAN#136]
If a CANOpen heartbeat frame is received it seems to show the proper length (1) but the actual data byte is not reported correctly.

**Comment by collin80** [comment]
I think this was due to an error where socketcan frames didn't get their data bytes copied over properly. Should try this again.

**Comment by joshwardell** [comment]
Would it be helpful to have some real CANopen logs? Let me know
