### ISSUE TITLE
Import from PCAN only in 11bit format ?

### ISSUE THREAD

**Issue by prensel** [collin80/SavvyCAN#156]
When importing trc files from PCAN they show up as 11bit ID's in the main screen whereas the 22bit ID's show in the right 'Frame Filtering screen'

**Comment by collin80** [comment]
It's very possible that I never had a TRC file with extended ID frames. Could you maybe post a snippet from the file where extended frames are so that I can make sure I'm correctly interpreting those lines too?

**Comment by prensel** [comment]
Here's a trace file from PCANView

[vx1-charge-plug.trc.txt](https://github.com/collin80/SavvyCAN/files/2488475/vx1-charge-plug.trc.txt)

**Comment by collin80** [comment]
Such files should load properly now as of this commit: b2c22ca21b4ec06014c71a27299f8f1ade8a1482
