### ISSUE TITLE
DBC Editor support for cyclic messages

### ISSUE THREAD

**Issue by karlding** [collin80/SavvyCAN#157]
Hi, I was playing around with SavvyCAN this week, and I managed to get it building from source pretty easily.

I was wondering if you planned on adding support for cyclic messages to SavvyCAN's DBC editor. It seems like you already handle parsing DBC attributes (in `dbc/dbchandler.cpp`), but as far as I can tell, the GUI doesn't provide a way to mark a message as cyclic (and set the period). Is this something that you're planning on adding, or are you just aiming to support the minimal subset of the DBC format that you need in order to provide SavvyCAN's functionality?

Thanks!

**Comment by collin80** [comment]
Moving wishlist items to wiki
