### ISSUE TITLE
Segfault when clicking signal

### ISSUE THREAD

**Issue by karlding** [collin80/SavvyCAN#158]
I was playing around with SavvyCAN and the DBC files over at CommaAI's [OpenDBC project](https://github.com/commaai/opendbc/), and I noticed that clicking on certain signals would cause SavvyCAN to segfault.

1. Use the `tesla_can.dbc` file
1. Click on the `ESP` node
1. Click on the `ESP_135h` message
1. Click on the `ESP_tcOffLamp` signal

Looking at CommaAI's DBC, it seems like they have `\r` characters on that [line](https://github.com/commaai/opendbc/blob/master/tesla_can.dbc#L150), so it seems like the parser isn't handling this correctly?

This same file seems to work fine in Kvaser Database Editor.

**Comment by collin80** [comment]
I can't reproduce this error in the latest source code. But, I can confirm that it does crash when using the V187 binary. So, it's fixed but only in WIP right now. I'm gearing up to move the changes back over to master and that should be happening some day soon.
