### ISSUE TITLE
Timestamp overwritten with msgID in mainwindow

### ISSUE THREAD

**Issue by vondraussen** [collin80/SavvyCAN#171]
The timestamp seems to be overwritten with the message ID in the main window trace.
Running on Windows

![](https://i.imgur.com/xqAdgeg.png)

**Comment by collin80** [comment]
I have a second report of this. But, I haven't experienced it myself. So, is it possible to tell me any more about when this happens? Do you always see this overwriting or does it randomly happen? I see the direction is transmission, does it happen to received frames? Does it happen when you load a file?

**Comment by vondraussen** [comment]
This happens always. Also if I load a file (Busmaster Logfile).

I cant say anything about if it happens while receiving as well, since my PEAK CAN seems not to work with savvyCAN. I copied the dll to the app root and I'm able to select the interface on *usb0* but it doesn't show anything in the trace. The interface works well with Busmaster.

**Comment by vondraussen** [comment]
Just tested with my fork and if I load the same log file, the time stamps are shown correctly.
![](https://imgur.com/r3snnZF.png)

My branch is based on master and shows **Savvy CAN V190** as window title. The release on your page says **V195**
Are there no tags for the versions?

**Comment by collin80** [comment]
I'm a schmuck and no, I keep forgetting to tag the releases. They're
all in there but I keep forgetting to tag them. You must be compiling
the master branch. V196 is the current version in WIP.

**Comment by collin80** [comment]
I fixed the issue here 9596d240ad1aa177033706deb8fcf1b1b3bb09ed

It turns out it seems to only happen on Windows 10 and maybe Windows 8. On Windows 7 where I normally test it worked fine. I have no idea why Windows 10 is different. But, the issue is solved.
