### ISSUE TITLE
Overwrite Mode - always on 

### ISSUE THREAD

**Issue by cdxa1** [collin80/SavvyCAN#173]
When I turn on Overwrite mode and accept the "Danger Will Robinson" window, everything is ok. But when I want to disable Overwrite mode it's still on, even with the unchecked option, the only way is to exit from savvy and start a new session. BTW counter of received frames in OM will be very usable, Timestamp sometimes is not enough.
Savvy V196

**Comment by collin80** [comment]
Bug fix for that massive oversight: 6c4ce692f1ad89f4129925f5d92b1036da4ce2e8
Addition of frame count (replaces Rem when in overwrite mode): a818a56c96cf12eeacddd6e3bcb400b32a927337

Both are in WIP currently. They'll be brought out to master and included when the next release happens. I don't know when that'll be but the changes are committed now if you feel like compiling it yourself.
