### ISSUE TITLE
New Connection Window - how to save current connections?

### ISSUE THREAD

**Issue by cdxa1** [collin80/SavvyCAN#174]
When I set up a new connection, and save, everything is ok. Until restart savvy, all saved connections disappear. So every start of savvy  I need to set up a new connection.
Savvy V196

**Comment by collin80** [comment]
Go into the preferences and select "Save/Restore CAN bus connections" and then it will save them and try to restore them. Some people might not want it to automatically do this so it is turned off by default. The connection system was recently overhauled so I'll keep this issue open and you can report if anything dumb happens.

**Comment by cdxa1** [comment]
Now it's much better. Thank you :)
