### ISSUE TITLE
Graph Data: difficult to find one message amongst many

### ISSUE THREAD

**Issue by nkirkby** [collin80/SavvyCAN#181]
using the `Graph Data` tool,
right-clicking and selecting `Add New Graph`,
with large DBCs, the `Message` drop-down menu gets unwieldy.

If I start typing the name of the message, I can sometimes get it.  However, the syntax requires an exact match, and the time in which to enter a name is very short.
For messages that have a common prefix, it's almost impossible to type the correct message name in time.  For example:
car_packErrors
car_packStatus

Some options that may improve this experience:
- sorting menu options alphabetically
- allowing searching that is case-insensitive
- allowing searching that matches a substring within a message name

**Comment by collin80** [comment]
As of faa0c8c9abe399e30686d357f27f0b57be51b4ec it now sorts messages and signals alphabetically so it should be easier to find things. Also there was a bug that would have stopped it from properly copying signals that were not found in the first loaded DBC file. The other two options (case insensitive search, substring search) could be possible but would require a bit more work.
