### ISSUE TITLE
Wishlist: Display cycle time in overwrite mode

### ISSUE THREAD

**Issue by nkirkby** [collin80/SavvyCAN#188]
For frames received periodically in overwrite mode, it would be useful to see the timestamp delta since the last received frame of the same (CAN ID, bus #)

Edit: adding some background.  These are some specifics that I find time delta useful for:
- the period of messages immediately obvious
- a jittery delta can indicate that a node has timing issues, or that the bus is overloaded and a message cannot be sent regularly, or ...

**Comment by collin80** [comment]
I could probably re-purpose the timestamp field to instead show time delta. I'm already re-purposing the RTR field to turn into frame counter when in overwrite mode as RTR and overwrite mode wouldn't make tons of sense together anyway.

**Comment by collin80** [comment]
Added in c47c74ebf37599b991cf2c8de24d2f5e70511d4f
