### ISSUE TITLE
Bug: In the Frame Data Analysis window, divide by zero exception occurs.

### ISSUE THREAD

**Issue by shutingrz** [collin80/SavvyCAN#203]
In the Frame Data Analysis window, if there is only one CAN frame in the ID, a divide by zero exception occurs and the program crashes.

The debug print at the time of the crash was below.
```
Floating point exception (core dumped)
```

The cause is the following code of "re/frameinfowindow.cpp".

```
intervalMean = intervalSum / sortedIntervals.size();
```

After changing the source code as follows, the program is now working properly.
```
--- 375,383 ----
          std::sort(sortedIntervals.begin(), sortedIntervals.end());
          uint64_t intervalStdDiv, intervalPctl5, intervalPctl95, intervalMean, intervalVariance = 0;
  
+         int maxTimeCounter = -1;
+         if (sortedIntervals.size() > 0) {
+ 
          intervalMean = intervalSum / sortedIntervals.size();
  
          for(int l = 0; l < sortedIntervals.size(); l++) {
***************
*** 411,416 ****
--- 414,420 ----
              avgInterval = avgInterval / (frameCache.count() - 1);
          else avgInterval = 0;
  
+ 	}
          tempItem = new QTreeWidgetItem();
  
          if (minLen < maxLen)
```

If you find that the same problem occurs in your environment, please refer to the above for correction.

**Comment by collin80** [comment]
Indeed, that would cause problems. I've implemented your fix and it is now committed as d3f9fd445d1267e73e6a9dfb94fb53baf994aee2

Thanks!
