### ISSUE TITLE
Cannot load DBC file on Mac OS 15.1 

### ISSUE THREAD

**Issue by dennis-d** [collin80/SavvyCAN#216]
Load button is not active , Cannot click any button but "Create new DBC"

**Comment by collin80** [comment]
Well that's peculiar. There is nothing in code that would intentionally disable the load button. So, I'm currently at a loss for why it would be doing that. I'll look into it and see what I can find.

**Comment by dennis-d** [comment]
The behavior is kind of weird, when I click Load button it actually clicks Create DBC, like it overlays everything

**Comment by exekutive** [comment]
which version are you using?
I'm using the latest (199) on MacOS 10.14 and it works fine. So it could be an OS thing.

I know that starting in Catalina, Apple is ending support for legacy 32 bit code.

**Comment by KostyaSha** [comment]
OSX 10.14.6, Qt 5.14.1  works fine
