### ISSUE TITLE
signal length

### ISSUE THREAD

**Issue by exekutive** [collin80/SavvyCAN#218]
In the DBC editor, I'm unable to enter 64 for bit length of a signal. That means values which have 8 data bytes (such as VIN number) are not possible. 63 seems to be the maximum.

**Comment by collin80** [comment]
Yeah, that seems like a bug. I'll leave this open until I get it fixed. Though, VIN numbers are far larger than 64 bits anyway so that leads to another thing I ought to support - signals that span multiple frames via ISO-TP or J1939.

**Comment by collin80** [comment]
I did fix this in code already. There is still no support for signals over ISO-TP but that's a separate thing.
