### ISSUE TITLE
Is this device compatible ?

### ISSUE THREAD

**Issue by AndKe** [collin80/SavvyCAN#229]
https://www.ebay.com/itm/264114364000

Also: 
I have an Saleae 16pro analyzer that can save the data as raw or decoded data... are you aware of any compatibility with Saleae logic software ?

**Comment by mitchdetailed** [comment]
Yes, it's capable of utilizing savvycan
Via the Linux 'socketcan' interface option.

**Comment by AndKe** [comment]
Great, I take that the injection/replay of frames will work too.
This is very nice, usually, I'd use a microcontroller to do this kind of reverse-engineering, but this seems much faster.
Merry Christmas.

**Comment by collin80** [comment]
Yes, getting access through socketcan will allow for injection and replay. A Saleae Logic 16 will be able to capture data but not send. And, there is no way to integrate Logic with SavvyCAN. Though, it might be an interesting idea to allow SavvyCAN to read Logic captures.

**Comment by mitchdetailed** [comment]
Raspberry pi + dual can-fd hat + pimoroni phat is what I'll be doing to
incorporate this. Just have to set event based actions within a script.
