### ISSUE TITLE
Creating a DBC file with an Extended CAN ID doesn't set the Extended bit in the ID

### ISSUE THREAD

**Issue by rscullin** [collin80/SavvyCAN#235]
When creating a DBC file using SavvyCAN, the Extended bit isn't set in the CAN ID when entering an extended ID. This causes issues loading the generated DBC file in other tools, such as Vector's [CANdb++ Editor](https://www.vector.com/int/en/products/products-a-z/software/candb/).

# To reproduce:
1. Create a new DBC file
2. Create a new node ("TestNode")
2. Add a new Extended Message ID (ex: `0x00123456`) to the created node
3. Save the DBC, and open with a text editor
4. Note that the ID value saved is `1193046`, which is `0x00123456` in decimal. It should have a leading bit set to indicate that it's an extended ID, so it should be `2148676694` instead.

I've also included a DBC  I generated in SavvyCAN following the above steps: [extended_savvycan_bug.dbc.txt](https://github.com/collin80/SavvyCAN/files/4424545/extended_savvycan_bug.dbc.txt) .

# Reference:
The [DBC File Format Documentation](http://read.pudn.com/downloads766/ebook/3041455/DBC_File_Format_Documentation.pdf), Page 4, Section **8 Message Definitions** :
>  If the most significant bit of the CAN-ID is set, the ID is an extended CAN ID. The extended CAN ID can be determined by masking out the most significant bit with the mask 0xCFFFFFFF.

# Error in CANdb++:
Error in CANdb++ Editor when using a DBC generated by SavvyCAN:
![image](https://user-images.githubusercontent.com/176014/78313917-55634e80-7526-11ea-9f95-69b5ac72b581.png)

**Comment by collin80** [comment]
It should be fixed as of 44aa622cd9973564e6fb382f23f98d2c40a18b4d committed to the WIP branch.
