### ISSUE TITLE
Receiving frames while filtering causes phantom records

### ISSUE THREAD

**Issue by collin80** [collin80/SavvyCAN#25]
If you have filtering enabled and are also still receiving traffic then you will likely see phantom records appear in the frame list. They won't have any data at all but they'll be numbered anyway. This isn't a big deal as they're harmless and go away when you change the filters. They don't affect anything but it's kind of annoying. So, it should be fixed.

**Comment by Mike4U** [comment]
I'll second its an issue.  When watching for filtered frames with autoscroll to see the latest, the latest is taken over by phantom records hiding the desired frames.

**Comment by collin80** [comment]
Problem fixed in V138
