### ISSUE TITLE
SavvyCAN 2.01 seems to randomly crash in window 10 proffessional

### ISSUE THREAD

**Issue by bvernham** [collin80/SavvyCAN#269]
The 32 bit version seems to be  OK though but the DBC managers is not nearly as nice.

**Comment by collin80** [comment]
I'll look into it. I do all my testing on Linux so the Windows build is less well tested. I do, however, have Windows 10 installed for dual booting so I can load up Windows and test it.

**Comment by bvernham** [comment]
PS great work on due_can.

1.99 is solid as a rock but you can search the DBC which is a nice feature.

Thanks

Bruce
