### ISSUE TITLE
Multiplexor after multiplexed signal does not work

### ISSUE THREAD

**Issue by BitterAndReal** [collin80/SavvyCAN#301]
The multiplexed signals are not recognised if the multiplexor is after the multiplexed signal in the CAN message.
I set up a test where I send the similar message with two ID's. 
One has the multiplexor signal in the first two bytes and the other in the last two. The multiplexed signals are in byte 2-5.
0x064 with the multiplexor in the beginning works fine
0x065 with the multiplexor in the end is not interpreted
I added printscreens and the DBC file I used for the test.

[mux test DBC.zip](https://github.com/collin80/SavvyCAN/files/6043067/mux.test.DBC.zip)

![mux test](https://user-images.githubusercontent.com/34364368/109155773-46097700-7770-11eb-8571-10ce8264a1f0.PNG)
![mux after](https://user-images.githubusercontent.com/34364368/109155808-4f92df00-7770-11eb-95ed-b533e780c649.PNG)
![mux first](https://user-images.githubusercontent.com/34364368/109155811-502b7580-7770-11eb-8bcd-d07552413ee4.PNG)
![multiplexed signal](https://user-images.githubusercontent.com/34364368/109155812-502b7580-7770-11eb-8886-6f58eb180e88.PNG)

**Comment by collin80** [comment]
I'll check this out. However, I'm currently totally rewriting the DBC code to support extended multiplexing. I believe my code changes will fix this problem as well.

**Comment by BitterAndReal** [comment]
That's nice! I like your work very much.

**Comment by collin80** [comment]
The code was checked in for extended multiplexing and I'd think it probably fixed this issue as well. So, if you get a chance, you might try again and see if things are working better. If so we can close this issue.

**Comment by BitterAndReal** [comment]
Thanks! I'll have a look...

**Comment by BitterAndReal** [comment]
I tested with the version 1.0.173 released on 19 Mar but I expierience the same problem.  
![MUX](https://user-images.githubusercontent.com/34364368/115710190-5d30a380-a372-11eb-86ad-718625cb7017.PNG)

**Comment by collin80** [comment]
Yes, apparently there was a bug that would not allow multiplexors to work if they are big endian and at the end of the frame. I've corrected that but haven't merged in the change to github yet. But, it should drop later today and then it should work both at the beginning and end.

**Comment by BitterAndReal** [comment]
Multiplexing is working perfect now. Thanks a lot!
