### ISSUE TITLE
[Linux] framefileio.cpp missing include <memory>

### ISSUE THREAD

**Issue by mickeyl** [collin80/SavvyCAN#310]
On my machine, I had to add #include <memory> in framefileio.cpp, otherwise it would bail out because of `std<unique_ptr>` not being found.

**Comment by collin80** [comment]
Hmmm, I am nearly always using linux and have not had to do this. But, I just checked and adding that include doesn't break anything on my machine. So, I've pushed it to master (9b84a46) and now it should compile as-is.
