### ISSUE TITLE
[Linux] Bump Qt5 version recommendation

### ISSUE THREAD

**Issue by mickeyl** [collin80/SavvyCAN#311]
From the README.md it looks like any Qt5 newer than 5.10 would do, which seems wrong. I just tried compiling with 5.12 and it bailed out on at least `QList.swapItemsAt` and `QComboBox::textActivated`.

**Comment by collin80** [comment]
You're right. The targeted version of QT keeps going up but I don't always remember to update the readme to match. This is fixed as of e91aeef1b6f9e97c2528e1e8d6d7b51459b593f3
