### ISSUE TITLE
Getting error regarding vcruntime140_1.dll

### ISSUE THREAD

**Issue by MatinF** [collin80/SavvyCAN#319]
We have a user getting an error as below:

"the code execution cannot proceed because vcruntime140_1.dll was not found"

![image](https://user-images.githubusercontent.com/26184427/111601243-745bfe80-87d2-11eb-8572-2d02942b11bc.png)

Is this a known issue - and if so is there a solution to it?

**Comment by collin80** [comment]
If you're using the pre-built binary releases then they should contain the Visual Studio redistributables installer. If you get errors like this then run that installer and it will install all the VS runtime files needed.
