### ISSUE TITLE
Where is the latest mac install dmg file?

### ISSUE THREAD

**Issue by patfelst** [collin80/SavvyCAN#371]
Hi there, I'd like to install the latest version on a mac. The releases only seem to have zip files which contain windows executables.
I did stumble across a dmg in the development buid under the 'continuous' tag. Here https://github.com/collin80/SavvyCAN/releases/tag/continuous

Is that the best place to start, or is there a stable version? I installed it on the lates MacOS Big Sur (11.4) and it seems to run fine. 

Thanks!

**Comment by collin80** [comment]
Yes, right now the continuous build is the best one to use.

**Comment by patfelst** [comment]
ok thanks!
