### ISSUE TITLE
Bug in normalize frame timing function.

### ISSUE THREAD

**Issue by joee-co** [collin80/SavvyCAN#409]
Hi author,
there are a small bug in the normalize frame timing function, when there is no frame or after clear frames action, if we restart to capture the frames again from suspend mode, it will not receive any frames, because it's locked, should add the unlock function before return.

BR and thanks very much for your shared codes

 CANFrameModel.cpp

 * Scan all frames for the smallest timestamp and offset all timestamps so that smallest one is at 0
*/    
void CANFrameModel::normalizeTiming()
{
    mutex.lock();
    if (frames.count() == 0)
    {
 **mutex.unlock();**

        return;
    }

**Comment by collin80** [comment]
You're right. I've added the unlock to code.
