### ISSUE TITLE
Cannot run on Ubuntu bionic

### ISSUE THREAD

**Issue by probonopd** [collin80/SavvyCAN#413]
Cannot run on Ubuntu bionic because it was built on a too new system:

```
AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2700

**Comment by collin80** [comment]
I just pushed a commit that causes GitHub Workflow to use Ubuntu 18.04 to compile instead of 20.04. This should fix the issue for you.

**Comment by probonopd** [comment]
Thank you very much @collin80 - I confirm that it is working now :+1:
