### ISSUE TITLE
Sniffer hide the id canbus

### ISSUE THREAD

**Issue by malparitdegardi** [collin80/SavvyCAN#477]
if you want view the bits in sniffer mode, the can bus id disappear.
![Captura de pantalla de 2022-06-18 00-25-38](https://user-images.githubusercontent.com/38014090/174408857-08a801f0-fd07-46e8-a1e4-f646eb5feecf.png)
![Captura de pantalla de 2022-06-18 00-25-41](https://user-images.githubusercontent.com/38014090/174408867-9056eac6-8c66-4699-a661-2be4bbcfac97.png)

**Comment by collin80** [comment]
Yes, that was a bug. I've fixed it as of e1ea668bd53bade47bc75d85342de6fdd1a213a1 and a new continuous build has succeeded so you can download the binary if you'd like.
