### ISSUE TITLE
Signal Viewer, only able to add one signal despite having multiple in dbc editor.

### ISSUE THREAD

**Issue by wakey1991** [collin80/SavvyCAN#490]
Hello.

I have added approx 5 signals to 2 different control units. However in signal viewer, i am only able to add 1, the first one i created.

Others do not appear in the drop down box.

Is there something i am missing? Thanks

**Comment by collin80** [comment]
That's weird. Maybe it's related to the other issue you created. I just tried with a known working DBC file and I can add multiple signals and see their status update.

**Comment by wakey1991** [comment]
This appears to have resolved itself this morning when I tried again. Thanks
