### ISSUE TITLE
UDS Read DTCs

### ISSUE THREAD

**Issue by stinkydiver73** [collin80/SavvyCAN#568]
UDS scanner Read DTCs sending 03 19 87 02, it's should be 03 19 02 xx. (xx could be FF for all type of DTC-s)

**Comment by collin80** [comment]
You're right. Those bytes were supposed to be flipped. It should have been 03 19 02 87. I can see in code that I used 0x87 on purpose but having gone back and read the standard I suppose I don't see any reason not to just go ahead and use 0xFF to request any sort of DTC at all for the purposes of the test.
