### ISSUE TITLE
UDS Scanner: Can't save SCAN sequence 

### ISSUE THREAD

**Issue by simoneScaravati** [collin80/SavvyCAN#602]
Hi there,
I'm on Ubuntu 20.04 LTS, SavvyCAN V208 (pre built image), testing bus with PEAK CAN usb device (socketcan interface under Linux).  
I'm using (Send Frames >) UDS scanner functionality and I found out that I can't save the scanning sequence properly. 
When I try to Save the scan sequence (Bottom left button SAVE), the program saves the file as a binary file. And when I try to Load a configuration (Bottom left button LOAD) the file doesn't show up in the file explorer! 
Is it a known bug? Am I doing something wrong? Or is it a real bug? 
Thanks for your work

**Comment by collin80** [comment]
Well, it looks to be incredibly broken at the moment. It appears I started to implement those functions and then... just didn't finish. Even in the bleeding edge version it's still broken. However, I can save and load and the file does show up when I try to load it. It even loads it. It just loads a corrupted mess. I'll get this fixed up.

**Comment by collin80** [comment]
It should work properly with the commit I just pushed bdc68b858e04af85dc0d3d0a74960418406f666d

If you use the continuous build that should be available (shortly) then it should be functional.

**Comment by simoneScaravati** [comment]
Confirm! I switched to master branch version and compiled my self the last commit and it works perfectly as you said! 
Thanks so much
Cheers
