### ISSUE TITLE
Bug: Playback crashes if no log file is loaded

### ISSUE THREAD

**Issue by MatinF** [collin80/SavvyCAN#604]
**Observed** 
Playback window currently allows the user to press "play" despite no log file being loaded in the lower left corner. The result is that SavvyCAN crashes.

**Expected**
Ideally, the user would instead be warned that they need to load a log file before attempting to playback anything.

**Comment by collin80** [comment]
Upcoming commit 044fea3 will fix this by issuing a warning dialog instead of attempting to continue. However, on Linux it doesn't seem to crash on me anyway.
