### ISSUE TITLE
Added support for a TouCAN adapters from Rusoku technologijos

### ISSUE THREAD

**Issue by rusoku** [collin80/SavvyCAN#611]
Released Qt 5.15.x open source serial bus (CAN bus) plugin for TouCAN adapter and Apple MacOS.
It supports up to eight adapters at the same time.
Any serial port devices ;-)
<img width="1198" alt="Rusoku_Toucan_conn" src="https://user-images.githubusercontent.com/46974254/227707085-fb13dcbe-86ad-4e70-bcdd-dbfe2da1cbee.png">

**Comment by mickeyl** [comment]
@rusoku Excellent. Is this already or will this appear in Qt 6?

**Comment by rusoku** [comment]
Released Qt 5.15.x open source serial bus (CAN bus) plugin for TouCAN adapter and Windows x64.
Plugin currently supports up to eight devices.
[www.rusoku.com/products](https://www.rusoku.com/storage/app/media/drivers/Windows/qtrusokucanbus.zip)

![Savvy_rusoku_win](https://github.com/collin80/SavvyCAN/assets/46974254/2ace7c7c-4ef4-4fe5-9184-ad3575a0eb77)
