### ISSUE TITLE
Interpreted frame goes black (with DBC)

### ISSUE THREAD

**Issue by nico0481** [collin80/SavvyCAN#641]
Hello,
When I try to interpret frame with DBC file, interpreted frame goes black and no more visible.
How is it possible to see interpreted frames in live?

![Screenshot_2023-05-31_23_24_22](https://github.com/collin80/SavvyCAN/assets/45109152/b14c178d-7322-474d-962f-0de6005e5060)

**Comment by collin80** [comment]
It's a known problem that pops up sometimes. DBC files can get saved with strange color combinations and then it seems to like to show black on black. Go to preferences and set "ignore DBC colors" and it won't do that. But, there are bugs that cause the DBC file to get to that point so what really needs to happen is that I find and fix the bugs.
