### ISSUE TITLE
'Save decoded frames CSV': Add option to remove 'units' and use 'date & time'

### ISSUE THREAD

**Issue by MatinF** [collin80/SavvyCAN#648]
Hi Collin,

The ability to save decoded frames as CSV is awesome, and the format is very intuitive.

We have received a couple of feedbacks from our users on this, though:

1) It would be great to be able to remove units from the exported frames. This way it's far easier to work with the data in e.g. Excel, scripts etc. This could be an option in the preferences, e.g. under a new 'CSV export settings' section where this option could be called `Include signal units` with an Enabled check mark as the default

2) It would also be neat to have the option of exporting the timestamp as an absolute date & time. For cross-country compatibility, the best way to do this may be that if the user has enabled `Absolute date & time` for the export in the Preferences, then the CSV output would have `Year,Month,Day,Hour,Minute,Second,Ms,Signal1,Signal2,...` as the structure. Default could be to disable this.

**Comment by collin80** [comment]
"1" is now the way it works. It does seem to make  more sense not to put the units at the end of all the values if they're going to be in a CSV file

"2" is now implemented. It's a preference that can be set. I've tested it both ways and it seems to work properly.
