### ISSUE TITLE
CANBUS data stops capturing / freezes in Main capture window

### ISSUE THREAD

**Issue by itaintpriddy** [collin80/SavvyCAN#662]
Hello I am quite new to this so please bear with me.

I recently purchased an EVTV ESP32 Candue board, went through the ups and downs of trying to get it to work (I'm not a very savvy programmer, more like 0 knowledge, total beginner), I finally got the unit to connect on Savvycan after a bit of trial and error compiling in Arduino IDE.  

I can only see a small snippet of data being captured on Savvycan before the counter under "Total Frames Captured" freezes.  When I first start my vehicle in "ACC" mode, I get to roughly 1700-1900 frames, when I switch to "ON" position it freezes after about 200-300 frames (if that).  I cannot seem to get a continuous stream of data to test functions of the vehicle. 
Any suggestions of what I may need to do?

I am connecting directly into the OBD2 port and tested the resistance, it showed approximately 40 ohms with the Candue connected. Wondering if this may be the cause. If so, is there a way to switch the termination resistor, so I get the whole connection to 60 ohms? (hope that makes sense).

Just for reference, I am running SavvyCan on a new laptop with Windows 11.

Appreciate any assistance. Thanks!

**Comment by collin80** [comment]
![20230605_190023_resized](https://github.com/collin80/SavvyCAN/assets/2145125/27e6da25-4ecf-493a-8b6c-3f327830f402)

To break termination on CAN0, remove either R13 or R14. To break termination on CAN1, remove either R2 or R3. Both are done with split termination which is a little bit more noise immune than a single 120 ohm resistor. But, removing just one of the resistors will break the circuit to the termination.

It's true, you really should have 60 ohms resistance on the CAN bus. Usually 120 (one side terminated) or 40 (three terminations) ohms still works for smaller buses but either can cause trouble.
