### ISSUE TITLE
Socketcan baud rate

### ISSUE THREAD

**Issue by collin80** [collin80/SavvyCAN#69]
At the moment it is not possible to set the baud rate of socketcan devices. This is because the QSerialbus interface does not expose any way to change the socketcan speed. And, the reason for that is that socketcan is a network interface and you have to basically bring the interface down, edit the baud, and bring it back up.  Because you can't edit the baud SavvyCAN just grays out the baud selection and you can't change it. But, it also has no idea what baud you have set so it is potentially reported wrong in the program. I'm not really sure how to resolve the oddity of this situation. Configuring socketcan is really something you are supposed to do on the command line and maybe it has to stay there. But, it makes things feel a bit weird within SavvyCAN.

**Comment by andre-hartmann** [comment]
This is effectively [QTBUG-54296](https://bugreports.qt.io/browse/QTBUG-54296).
But even if you can set the bitrate with a library, you need to run your program with privileges to do so.
