### ISSUE TITLE
Who asks for Vehicle Speed?

### ISSUE THREAD

**Issue by mfide** [collin80/SavvyCAN#755]
Hello,

I have an OBD2 and SavvyCAN specific question.

As soon as I connect OBD2 port of my car to SavvyCan using Korlan USB2CAN adapter, I see a traffic that includes Vehicle Speed broadcasted periodically without asking.

![image](https://github.com/collin80/SavvyCAN/assets/10511625/76e6fc7f-ca73-40f5-8479-9b26a0c8a2bc)

But whenever I connect to the car using my custom program/hardware other than Savvy and Korlan, I have to explicitly ask for vehicle speed to get response from the car. Like: TX - 7DF [8] 02 01 0D CC CC CC CC CC to request vehicle speed and car replies with RX - 7E8 [4] 03 41 0D 18.

Does Savvy send a request automatically for vehicle speed but hide that traffic in the communication window, or something else going on?

Thank you.

**Comment by nickdaria** [comment]
SavvyCAN starts passively and does not send anything. Anything it does send will be marked in the Dir column as Tx instead of Rx.
