### ISSUE TITLE
Custom frame sender not working in latest commit/dev build

### ISSUE THREAD

**Issue by MatinF** [collin80/SavvyCAN#756]
Hi Collin,

I seem to be unable to use the Custom frame sender in the latest dev build, just as an FYI. 

See below video:
https://github.com/collin80/SavvyCAN/assets/26184427/3f7c6430-65ac-444e-b8a6-589c05c78a80

This works in older versions of the GUI.

**Comment by collin80** [comment]
I'm going to look into fixing this in the very near future. It seems a little bit of upcoming changes were merged in (by some mysterious dum-dum who I won't name) and that probably broke it.

**Comment by MatinF** [comment]
Thanks! I like the way the frame sender is integrated into the bottom main window, though. If you get the chance to incorporate some of the other feedback points on this view it would be awesome: https://github.com/collin80/SavvyCAN/issues/361#issuecomment-1482534477

**Comment by MatinF** [comment]
It looks like this has been resolved

**Comment by zalexzperez** [comment]
I'm currently trying version V220 built May9 2025 in a Windows 11 machine and it's also not working. Same behavior like in the video.
Fortunately, I can still send messages using the panel at the bottom of the main screen, although you can't save/load messages there.
