### ISSUE TITLE
Timestamps on Windows are not human-readable

### ISSUE THREAD

**Issue by SebKuzminsky** [collin80/SavvyCAN#781]
# Good on Linux

On a local Linux build of commit 67dfaf1, the timestamps look very clear and understandable:
![Screenshot from 2024-05-13 14-40-41](https://github.com/collin80/SavvyCAN/assets/400548/d71523cf-3ed5-48db-b1a9-07e4a4a3d838)

# Bad on WIndows
However, on the Windows build (exe downloaded from the github CI build of that commit) the timestamps look "raw", no matter if `Normalize Frame Timing` is clicked or not:
![image](https://github.com/collin80/SavvyCAN/assets/400548/db3419eb-67a8-4c44-b039-0767335711b2)
![image (1)](https://github.com/collin80/SavvyCAN/assets/400548/2826fbbc-8148-4ef0-a235-d7469e39a474)

**Comment by collin80** [comment]
In the preferences, see what the time stamp format is set to. I'll bet it is set differently for each of your operating systems. The Windows time stamps look like microseconds. If you set it to seconds that would look a little better. If you set it to system clock instead then it'll look like what the Linux version looks like.

**Comment by SebKuzminsky** [comment]
Ah, thanks, I'll take a look and get back to you!

**Comment by SebKuzminsky** [comment]
You're right, fixing it in Preferences worked.  So this is operator error on my part.  Thanks!
