### ISSUE TITLE
dbc bug?

### ISSUE THREAD

**Issue by dimavs** [collin80/SavvyCAN#83]
Looks like a bug to me
https://github.com/collin80/SavvyCAN/blob/master/dbc/dbchandler.cpp#L434

Shouldn't it be "11 + offset"?

**Comment by collin80** [comment]
Yes, it looks like you're correct. I'll fix that soon.

**Comment by collin80** [comment]
Fixed with 82550237ee50884768af5e7a7db82c6563c8af8f
