### ISSUE TITLE
Question: Bytes with different scaling in DBC Signal definition

### ISSUE THREAD

**Issue by wrightwells** [collin80/SavvyCAN#836]
Is it possible to join bytes in a signal definition with differnt scaling. 
I have been given the follwowing example 
ODO = 0.1 * buf[0] + 25.6 * buf[1] + 6553.5 * buf[2];

**Comment by collin80** [comment]
That isn't really different scaling, that's a 24 bit integer and 0.1 scaling. Specifically, it's a little endian 24 bit integer.

So, yes, create a signal that is little endian, 24 bits, and has a 0.1 scaling factor.
