### ISSUE TITLE
Playback: id 0x0CF00400 sent as 0x400

### ISSUE THREAD

**Issue by mr2c12** [collin80/SavvyCAN#856]
Log collected with PCAN-View in .trc format.
Other messages are sent just fine.

Got a problem with messages on id 0x0CF00400.
They are sent with id 0x400.

As per my understanding, the initial "0", before "C", is ignored and - therefore - the final id is only 28 bit. That is not enough to produce an extended id.

Can this be fixed?

Example of trace entry:

>     30)      2427.0  Rx     0CF00400  8  F8 7D 7D 00 00 00 00 00 

Result in Savvy (as sent by savvy itself):

![image](https://github.com/user-attachments/assets/5aa4dd5b-6133-4a16-9649-42095fd71d20)

**Comment by collin80** [comment]
Indeed, the file loader for PCAN files was only categorizing frames as extended if they had the 29th bit set. But, that's stupid - what's worse, I wrote that code so it's entirely my fault and I can't even blame anyone else. Now it goes extended if the ID is past 0x7FF which is the highest 11 bit ID possible. Now, technically it is possible and valid to have extended IDs that are 0x7FF and below. But, no one does that.

The QT6WIP branch  just got a commit pushed that fixes the issue. Github will automatically build the source and create a binary release.
