### ISSUE TITLE
Modify connections setting

### ISSUE THREAD

**Issue by guoh27** [collin80/SavvyCAN#859]
Can I change connection setting of existing connections?
![image](https://github.com/user-attachments/assets/c0125d8d-c4dc-41b5-ac82-488eab531211)
Here just add and remove

**Comment by collin80** [comment]
Yes, it's supposed to update the connection settings when you click save bus settings. In practice, this does not always happen quite like it should. Bugs should be reported for any interface where the changes don't seem to stick. One thing that definitely won't work is socketcan interfaces. They're configured on the command line so you can't actually change any off the settings from within SavvyCAN.
