### ISSUE TITLE
Support ISO-TP extended addressing

### ISSUE THREAD

**Issue by Semant1ka** [collin80/SavvyCAN#95]
Hi, 
I've seen a neat option in ISO-TP handler which enables extended addressing parsing, it seems to work fine, maybe it should be included in iso-tp window?
Also, the iso-tp window is not closing after main window closes.
So...I can add those things to iso-tp window and create a pull request. May I ?

**Comment by collin80** [comment]
Yes, by all means, if you'd like to fix those issues I'd be happy to merge
the changes in. Thanks.
